config/routes.rb
  EnterpriseCollab::Application.routes.draw do
  
  devise_for :users, :controllers => {:registrations => "users/registrations"}
  authenticated :user do
    resources :users
    post "users/new_user_create" => "users#new_user_create"
  end

  get "accounts/cron_tasks" => "accounts#cron_tasks"
  resources :accounts

  resources :dashboard

  resources :spaces
  get "spaces/milestones/:id/:filter" => "spaces#milestones"
  get "spaces/team/:id" => "spaces#team"

  resources :groups

  get "standup_reports/daily_email" => "standup_reports#daily_email"
  resources :standup_reports

  root 'home#index'
  

end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :account
  belongs_to :user

  # validates :name, :description, :presence => true
  validates :name, length: 1..50
  validates :description, length: 5..200


  def self.get_all(account_id=nil)
    account_id.blank? ? Group.all : Group.where(:account_id => account_id)
  end

  def self.create_group(params, account_id)
    member_ids = params[:member_ids].join(',') unless params[:member_ids].blank?
    group = Group.new(params)
    group.account_id = account_id
    group.status = true
    group
  end

  # Convert array to CSV
  # @param Array [1,2,3]
  # @returns String "1,2,3"
  def self.array_to_csv(arr)
    arr.delete("")
    arr.join(",")
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_filter :authenticate_user!

  # List all Groups for account
  def index
    @groups = Group.get_all(current_user.account_id)
  end

  # New Group Form
  def new
    @group = Group.new
    @users = User.get_all(current_user.account_id)
  end

  # Create Group
  def create
    # binding.pry
    @group = Group.create_group(group_params, current_user.account_id)
    @users = User.get_all(current_user.account_id)
    begin
      @group.save!
      flash[:success] = "Group was created successfully!"
      @groups = Group.get_all(current_user.account_id)
    rescue
      flash[:alert] = "Group creation failed!"
    end
  end

  # Edit Group form
  def edit
    @group = Group.where(:id => params[:id]).first
    @users = User.get_all(current_user.account_id)
  end

  # Update Group
  def update
    @group = Group.where(:id => params[:id]).first
    # binding.pry
    @users = User.get_all(current_user.account_id)
    begin
      # params['group']['member_ids'] = Group.array_to_csv(params['group']['member_ids'])
      @group.update_attributes!(group_params) 
      @groups = Group.get_all(current_user.account_id)
      flash[:succes] = "Group details updated successfully!"
    rescue => e
      flash[:alert] = "There was a problem updating the group details"
    end
  end

  def destroy
   @group = Group.where(:id=>params[:id]).first
   begin
    @group.destroy
    @groups = Group.get_all(current_user.account_id)
    flash[:succes] = "Group deleted successfully!"
    rescue 
      @users = User.get_all(current_user.account_id)
      flash[:alert] = "There was a problem in deleting the group"
    end
    # render :index, :groups => @groups
    # respond_to do |format|
    #   format.html { redirect_to groups_url }
    #   format.json { head :no_content }
    # end
  end
  ###############################################################################################################
  private
  ###############################################################################################################

  # Permit parameters
  def group_params
    params.require(:group).permit(:name, :description, :status, :user_id, :member_ids => [])
  end

end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<script type="text/javascript">
    
</script>

<%= form_for(@group, :html => {:class => "smart-form"}, :remote => true) do |f| %>
  <fieldset>
    <section>
      <label class="label"><strong>What would like to name your Group?</strong></label>
      <label class="input">
          <%= wrap_input_field("#{f.text_field :name, :'placeholder' => 'Group Name'}", "fa fa-group") %>
      </label>
    </section>

    <section>
      <label class="label"><strong>Write some Description for your group</strong></label>
      <label class="textarea">
          <%= wrap_input_field("#{f.text_area :description, :class => 'col-md-12' }", "") %>
      </label>
    </section>
  </fieldset>
  <fieldset>
    <section>
      <label class="label"><strong>Choose Owner</strong></label>
      <label class="select">
          <%= wrap_input_field("#{f.select :user_id, options_for_user_select(users), :class => 'select' }", "") %>
          <i></i>
      </label>
    </section>
  </fieldset>
 
  <fieldset>
    <section>
      <label class="label"><strong>Group Members</strong></label>
      <div class="row">
        <% 
          member_ids = []
          unless @group.member_ids.blank?
            group_member_ids = @group.member_ids.tr("\"---\n-", '').split(' ') 
            member_ids.push(@group.user_id.to_s) if (@group.member_ids.blank? ||  !group_member_ids.include?(@group.user_id.to_s) ) # Group Owner is by default group member
            member_ids = member_ids | group_member_ids
          end
         %>
        <% users.each do |u| %>
        <div class="col col-3">
          <label class="checkbox">
            <% checked = member_ids.include?(u.id.to_s) ? "checked='checked'" : "" %>
            <input type="checkbox" <%= checked %> name="group[member_ids][]" value="<%= u.id %>">
            <i></i><%= u.name %>
          </label>
        </div>
        <% end %>
      </div>
      <!-- <label class="select select-multiple">
          <%#= wrap_input_field("#{f.select :member_ids, options_for_user_select(users),{},{multiple: true, include_blank: true, :class => 'custom-scroll'} }", "") %>
          <i></i>
      </label> -->
    </section>

  </fieldset>

   <footer>
      <%= f.submit :class => "btn bg-color-green txt-color-white" %> 
    </footer>

<% end %>

app/views/groups/_index.html.erb
<div>
  <div class="pull-left">Lists all users.</div>
  <div class="pull-right">
    <%= link_to "<i class='glyphicon glyphicon-plus'></i> Add Group".html_safe, new_group_path, {:remote => true, :class=>"btn btn-info btn-sm"} if is_admin? %>
  </div>
</div>

<p class="clearfix"></p>

<%= render :partial => "list", :locals => { :groups => groups } %>

app/views/groups/_list.html.erb
<% active_groups = 0 %>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Owner</th>
      <th>Created At</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody> 
  <% if groups.blank? %>
    <tr>
      <td colspan="5" class="text-center text-muted">NOTHING FOUND!</td>
    </tr>
  <% else %>
    <% groups.each do |r| %>
      <tr>
        <td>
          <%= r['name'] %><code><%= SettingsConfig::STATUS[r['status']] %></code>
        </td>
        <td><%= r['description'] %></td>
        <td><%= r.user.name %></td>
        <td><%= CommonUtils.date_format(r['created_at'], "date") %></td>
        <td><%= link_to "<i class='fa fa-edit'></i>".html_safe, edit_group_path(r), :remote => true if is_admin? %>
           <span class="text-muted">|</span><%= link_to "<i class='fa fa-trash-o'></i>".html_safe, group_path(r), method: :delete, data: {confirm: "Are you sure, you want to delete this group?"},:remote => true if is_admin? %></td>
      </tr>
      <% active_groups = (active_groups + 1) if enabled?(r['status']) %>
      <% end %>
  <% end %>
  </tbody>
</table>

<% stat_count = groups.blank? ? 0 : (active_groups*100)/groups.size %>  

<script type="text/javascript">
// Update Active Statistics Count
  $(document).ready( function () {
    init(<%= stat_count %>);
  });

</script>

app/views/groups/_new.html.erb
<div>
  <div class="pull-left">Create a New Group</div>
  <div class="pull-right">
    <%= link_to "<i class='fa fa-reorder'></i> List".html_safe, groups_path, {:class=>"btn btn-info btn-sm"} %>
  </div>
</div>  

<p class="clearfix"></p>

<%= render :partial => "form", :locals => { :groups => @groups, :users => @users } %>

app/views/groups/_quick_snap.html.erb
<ul class="" id="sparks">
    <li class="sparks-info">
      <h5> Total Groups <span class="txt-color-blue"><%= groups.size %></span></h5>
      <div class="sparkline txt-color-blue hidden-mobile hidden-md hidden-sm"><canvas style="display: inline-block; width: 89px; height: 26px; vertical-align: top;" width="89" height="26"></canvas></div>
    </li>
    <li class="sparks-info">
      <h5>Active Groups <span id="stat-count" class="txt-color-purple"> </span></h5>
      <div class="sparkline txt-color-purple hidden-mobile hidden-md hidden-sm"><canvas style="display: inline-block; width: 82px; height: 26px; vertical-align: top;" width="82" height="26"></canvas></div>
    </li>
    
  <ul>

app/views/groups/create.js.erb
$('#flash-messages').html("<%= escape_javascript(render 'common/flash_messages') %>");
<% if flash[:alert].blank? %>
  $('#widget-content').html("<%= escape_javascript(render 'groups/list',:groups => @groups) %>")
<% else %>
  $('#widget-content').html("<%= escape_javascript(render 'groups/new',:group => @group) %>")
<% end %>

app/views/groups/destroy.js.erb
$('#flash-messages').html("<%= escape_javascript(render 'common/flash_messages') %>");
$('#widget-content').html("<%= escape_javascript(render 'groups/index',:groups => @groups) %>")

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/edit.js.erb
$('#widget-content').html("<%= escape_javascript(render 'groups/new',:group => @group) %>")

app/views/groups/index.html.erb
<% content_for :quick_snap do %>
  <%= render :partial => "quick_snap", :locals => { :groups => @groups } %>
<% end %>

<div class="row">
  <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12 sortable-grid ui-sortable">
    <div id="wid-id-0" class="jarviswidget jarviswidget-color-darken jarviswidget-sortable">
      <header role="heading">
        <%= render :partial => "common/admin/widget_title", :locals => {:title => "Groups"} %>
      </header>
      <div role="content">

          <!-- widget edit box -->
          <div class="jarviswidget-editbox">
            <!-- This area used as dropdown edit box -->

          </div>
          <!-- end widget edit box -->

          <!-- widget content -->
          <div id="widget-content" class="widget-body">
            <%= render :partial => "index", :locals => {:groups => @groups} %>

          </div> <!-- ENDs widget-content -->

        </div>

    </div>
  </article>

</div>

app/views/groups/new.html.erb
<h1>Create new Group</h1>
<%= render 'form' %>
<%= link_to 'Back', groups_path %>

app/views/groups/new.js.erb
$('#widget-content').html("<%= escape_javascript(render :partial => 'new') %>");

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name</strong>
  <%= @group.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @group.description %>
</p>

<p>
  <strong>Owner</strong>
  <%= @group.owner %>
</p>

<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>

app/views/groups/update.js.erb
$('#flash-messages').html("<%= escape_javascript(render 'common/flash_messages') %>");
<% if flash[:alert].blank? %>
  $('#widget-content').html("<%= escape_javascript(render 'groups/index',:groups => @groups) %>")
<% else %>
  $('#widget-content').html("<%= escape_javascript(render 'groups/form',:group => @group) %>")
<% end %>