config/routes.rb
  EnterpriseCollab::Application.routes.draw do
  
  devise_for :users, :controllers => {:registrations => "users/registrations"}
  authenticated :user do
    resources :users
    post "users/new_user_create" => "users#new_user_create"
  end

  get "accounts/cron_tasks" => "accounts#cron_tasks"
  resources :accounts

  resources :dashboard

  resources :spaces
  get "spaces/milestones/:id/:filter" => "spaces#milestones"
  get "spaces/team/:id" => "spaces#team"

  resources :groups

  get "standup_reports/daily_email" => "standup_reports#daily_email"
  resources :standup_reports

  root 'home#index'
  

end

app/views/common/admin/_breadcrumb.html.erb
<div id="ribbon">
  <span class="ribbon-button-alignment">
     <span data-html="true" data-original-title="&lt;i class='text-warning fa fa-warning'&gt;&lt;/i&gt; Warning! This will reset all your widget settings." data-placement="bottom" rel="tooltip" data-title="refresh" class="btn btn-ribbon" id="refresh">
      <i class="fa fa-refresh"></i>
     </span>
  </span>
  <ol class="breadcrumb">
    <li>Home</li><li>Dashboard</li>
  </ol>
</div>

app/views/common/admin/_header.html.erb
<!-- PLACE YOUR LOGO HERE -->
<div id="logo-group">
  <span id="logo"><%= link_to image_tag("smartadmin/logo.png"), root_path %></span>
  <!-- END LOGO PLACEHOLDER -->
  <%= render "common/admin/notifications" %>
</div>

<%= render "common/admin/projects" %>
<!-- end projects dropdown -->

<%= render "common/flash_messages", :locals => {flash => flash } %>

<!-- pulled right: nav area -->
<div class="pull-right">
 <%= render "common/admin/nav" %> 
</div>
<!-- end pulled right: nav area -->

app/views/common/admin/_left_bar.html.erb
<aside id="left-panel">
      
      <!-- User info -->
      <div class="login-info">
        <span>
          <!-- User image size is adjusted inside CSS, it should stay as it --> 
        <%= image_tag("smartadmin/chandrika.jpg")%> 
          <a href="javascript:void(0);" id="show-shortcut">chandrika <i class="fa fa-angle-down"></i></a>
        </span>
      </div>
      <!-- end user info -->
        <nav>
        <ul>
          <li class=""><a href="ajax/dashboard.html" title="Dashboard"><i class="fa fa-lg fa-fw fa-home"></i>  <span class="menu-item-parent">Dashboard</span></a></li>
          <li><a href="ajax/inbox.html"><i class="fa fa-lg fa-fw fa-inbox"></i>  <span class="menu-item-parent">Inbox</span><span class="badge pull-right inbox-badge">14</span></a></li>
          <li><a href="#"><i class="fa fa-lg fa-fw fa-bar-chart-o"></i>  <span class="menu-item-parent">Graphs</span></a>
            <ul>
              <li><a href="ajax/flot.html">Flot Chart</a></li>
              <li><a href="ajax/morris.html">Morris Charts</a></li>
              <li><a href="ajax/inline-charts.html">Inline Charts</a></li>
            </ul>
          </li>
          <li><a href="#"><i class="fa fa-lg fa-fw fa-table"></i>  <span class="menu-item-parent">Tables</span></a>
              <ul>
                 <li><a href="ajax/table.html">Normal Tables</a></li>
                 <li><a href="ajax/datatables.html">Data Tables</a></li>
              </ul>
          </li>
          <li><a href="#"><i class="fa fa-lg fa-fw fa-pencil-square-o"></i>  <span class="menu-item-parent">Forms</span></a>
            <ul>
               <li><a href="ajax/form-elements.html">Smart Form Elements</a></li>
               <li><a href="ajax/form-templates.html">Smart Form Layouts</a></li>
               <li><a href="ajax/validation.html">Smart Form Validation</a></li>
               <li><a href="ajax/bootstrap-forms.html">Bootstrap Form Elements</a></li>
               <li><a href="ajax/plugins.html">Form Plugins</a></li>
               <li><a href="ajax/wizard.html">Wizards</a></li>
               <li><a href="ajax/other-editors.html">Bootstrap Editors</a></li>
               <li><a href="ajax/dropzone.html">Dropzone <span class="badge pull-right inbox-badge bg-color-yellow">new</span></a></li>
            </ul>
          </li>
          <li><a href="#"><i class="fa fa-lg fa-fw fa-desktop"></i>  <span class="menu-item-parent">UI Elements</span></a>
            <ul>
               <li><a href="ajax/general-elements.html">General Elements</a></li>
               <li><a href="ajax/buttons.html">Buttons</a></li>
               <li><a href="#">Icons</a>
                <ul>
                   <li><a href="ajax/fa.html"><i class="fa fa-plane"></i> Font Awesome</a>
                   <li><a href="ajax/glyph.html"><i class="glyphicon glyphicon-plane"></i> Glyph Icons </a> 
                </ul>
               </li>
               <li><a href="ajax/grid.html">Grid</a></li>
               <li><a href="ajax/treeview.html">Tree View</a></li>
               <li><a href="ajax/nestable-list.html">Nestable Lists</a></li>
               <li><a href="ajax/jqui.html">JQuery UI</a></li>
            </ul>
          </li>
          <li><a href="#"><i class="fa fa-lg fa-fw fa-folder-open"></i>  <span class="menu-item-parent">6 Level Navigation</span></a>
            <ul>
              <li><a href="#"><i class="fa fa-fw fa-folder-open"></i> 2nd Level</a>
                <ul>
                   <li><a href="#"><i class="fa fa-fw fa-folder-open"></i> 3ed Level </a>
                    <ul>
                       <li><a href="#"><i class="fa fa-fw fa-file-text"></i> File</a></li>
                       <li><a href="#"><i class="fa fa-fw fa-folder-open"></i> 4th Level</a>
                        <ul>
                           <li><a href="#"><i class="fa fa-fw fa-file-text"></i> File</a></li>
                           <li><a href="#"><i class="fa fa-fw fa-folder-open"></i> 5th Level</a>
                            <ul>
                              <li><a href="#"><i class="fa fa-fw fa-file-text"></i> File</a></li>
                              <li><a href="#"><i class="fa fa-fw fa-file-text"></i> File</a></li>
                            </ul>
                           </li>
                        </ul>
                       </li>
                    </ul>
                   </li>
                </ul>
               </li>
               <li><a href="#"><i class="fa fa-fw fa-folder-open"></i> Folder</a>
                
                <ul>
                   <li><a href="#"><i class="fa fa-fw fa-folder-open"></i> 3ed Level </a>
                    <ul>
                       <li><a href="#"><i class="fa fa-fw fa-file-text"></i> File</a></li>
                       <li><a href="#"><i class="fa fa-fw fa-file-text"></i> File</a></li>
                    </ul>
                   </li>
                </ul>
                
               </li>
            </ul>
          </li> 
          <li><a href="ajax/calendar.html"><i class="fa fa-lg fa-fw fa-calendar"><em>3</em></i>  <span class="menu-item-parent">Calendar</span></a></li>
          <li><a href="ajax/widgets.html"><i class="fa fa-lg fa-fw fa-list-alt"></i>  <span class="menu-item-parent">Widgets</span></a></li>
          <li><a href="ajax/gallery.html"><i class="fa fa-lg fa-fw fa-picture-o"></i>  <span class="menu-item-parent">Gallery</span></a></li>
          <li><a href="ajax/gmap-xml.html"><i class="fa fa-lg fa-fw fa-map-marker"></i>  <span class="menu-item-parent">Google Map Skins</span><span class="badge bg-color-greenLight pull-right inbox-badge">9</span></a></li>         
          <li><a href="#"><i class="fa fa-lg fa-fw fa-windows"></i>  <span class="menu-item-parent">Miscellaneous</span></a>
            <ul>
               <li><a href="ajax/typography.html">Typography</a></li>
               <li><a href="ajax/pricing-table.html">Pricing Tables</a></li>
               <li><a href="ajax/invoice.html">Invoice</a></li>
               <li><a href="login.html" target="_top">Login</a></li>
               <li><a href="register.html" target="_top">Register</a></li>
               <li><a href="lock.html" target="_top">Locked Screen</a></li>
               <li><a href="ajax/error404.html">Error 404</a></li>
               <li><a href="ajax/error500.html">Error 500</a></li>
               <li><a href="ajax/blank_.html">Blank Page</a></li>
               <li><a href="ajax/email-template.html">Email Template</a></li>
               <li><a href="ajax/search.html">Search Page</a></li>
               <li><a href="ajax/ckeditor.html">CK Editor</a></li>
            </ul>
          </li>           
        </ul>
      </nav>
      <span class="minifyme">
        <i class="fa fa-arrow-circle-left hit"></i>
      </span>

      
    </aside>
    <!-- END NAVIGATION -->

app/views/common/admin/_main_nav.html.erb
<aside id="left-panel">
  <div class="login-info" style="">
    <span>
      <!-- User image size is adjusted inside CSS, it should stay as it --> 
      <%= image_tag "smartadmin/avatars/sunny.png", :class=>"online" %>
      <a id="show-shortcut" href="javascript:void(0);"><%= (current_user.first_name + " " +current_user.last_name)[0,11] %> <i class="fa fa-angle-down"></i></a>
    </span>
  </div>
  <nav>
    <ul>
      <li class="active">
        <%= link_to '<i class="fa fa-lg fa-fw fa-home"></i>  <span class="menu-item-parent">Dashboard</span>'.html_safe, dashboard_index_path  %>
      </li>
      <li>
        <%= link_to '<i class="fa fa-lg fa-fw fa-desktop"></i>  <span class="menu-item-parent">Spaces</span>'.html_safe, spaces_path  %>
      </li>
      <li>
        <%= link_to '<i class="fa fa-lg fa-fw fa-group"></i>  <span class="menu-item-parent">Groups</span>'.html_safe, groups_path %>
      </li>
      <li>
         <%= link_to '<i class="fa fa-lg fa-fw fa-user"></i> Users'.html_safe, users_path  %>
      </li>
      <li>
        <%= link_to '<i class="fa fa-lg fa-fw fa-home"></i>  <span class="menu-item-parent">Standup</span>'.html_safe, standup_reports_path  %>
      </li>
      <li>
        <%= link_to '<i class="fa fa-lg fa-fw fa-table"></i>  <span class="menu-item-parent">Timeline</span>'.html_safe, ""  %>
      </li>
      <li>
        <%= link_to '<i class="fa fa-lg fa-fw fa-calendar"><em>3</em></i>  <span class="menu-item-parent">ToDos</span>'.html_safe, ""  %>
      </li>
      <li>
        <%= link_to '<i class="fa fa-lg fa-fw fa-bar-chart-o"></i>  <span class="menu-item-parent">Reports</span>'.html_safe, ""  %>
      </li>
      <li>
        <%= link_to '<i class="fa fa-lg fa-fw fa-windows"></i>  <span class="menu-item-parent">Administration</span>'.html_safe, "#"  %>
        <ul>
          <% if is_admin? %>
          <li>
             <%= link_to '<i class="fa fa-lg fa-fw fa-globe"></i> Organization'.html_safe, edit_account_path(current_user.account_id)  %>
          </li>
          <% end %>
          <li>
             <%= link_to '<i class="fa fa-lg fa-fw fa-lock"></i> Roles &amp; Privileges'.html_safe, ""  %>
          </li>
          <li>
             <%= link_to '<i class="fa fa-lg fa-fw fa-group"></i> Groups'.html_safe, ""  %>
          </li>
          <li>
             <%= link_to '<i class="fa fa-lg fa-fw fa-user"></i> Users'.html_safe, "#"  %>
          </li>
        </ul>
      </li>
      <li>
        <%= link_to '<i class="fa fa-lg fa-fw fa-windows"></i>  <span class="menu-item-parent">Utilities</span>'.html_safe, "#"  %>
        <ul>
          <li><%= link_to '<i class="fa fa-lg fa-fw fa-cog"></i> Cron Tasks'.html_safe, controller: "accounts", action: "cron_tasks"  %></li>
        </ul>
      </li>
    </ul>
  </nav>

  <span class="minifyme">
    <i class="fa fa-arrow-circle-left hit"></i>
  </span>

</aside>

app/views/common/admin/_nav.html.erb
 <!-- collapse menu button -->
        <div class="btn-header pull-right" id="hide-menu">
          <span>
            <a title="Collapse Menu" href="javascript:void(0);"><i class="fa fa-reorder"></i></a>
          </span>
        </div>
        <!-- end collapse menu -->
        
        <!-- logout button -->
        <div class="btn-header transparent pull-right" id="logout">
          <span>
            <%= link_to('<i class="fa fa-sign-out"></i>'.html_safe, destroy_user_session_path, :method => :delete) %>
          </span>
        </div>
        <!-- end logout button -->
      
        <!-- search mobile button (this is hidden till mobile view port) -->
        <div class="btn-header transparent pull-right" id="search-mobile">
          <span>
            <a title="Search" href="javascript:void(0)"><i class="fa fa-search"></i></a>
          </span>
        </div>
        <!-- end search mobile button -->
        
        <!-- input: search field -->  
        <form class="header-search pull-right" action="#ajax/search.html">
          <input type="text" id="search-fld" placeholder="Find reports and more">
          <button type="submit">
            <i class="fa fa-search"></i>
          </button>
          <a title="Cancel Search" id="cancel-search-js" href="javascript:void(0);"><i class="fa fa-times"></i></a>
        </form> 
        <!-- end input: search field -->          
        
        <!-- multiple lang dropdown : find all flags in the image folder -->  
        <ul class="header-dropdown-list hidden-xs">
          <li>
            <a data-toggle="dropdown" class="dropdown-toggle" href="#">
              <%= image_tag "smartadmin/flags/us.png" %>
              <span>
                US
              </span>
              <i class="fa fa-angle-down"></i>
            </a>
            <ul class="dropdown-menu pull-right">
              <li class="active"><a href="javascript:void(0);"><%= image_tag "smartadmin/flags/us.png" %> US</a></li>
              <li><a href="javascript:void(0);"><%= image_tag "smartadmin/flags/es.png" %> Spanish</a></li>
              <li><a href="javascript:void(0);"><%= image_tag "smartadmin/flags/de.png" %> German</a></li>
            </ul>
          </li>
        </ul>
        <!-- end multiple lang -->

app/views/common/admin/_notifications.html.erb
<!-- Note: The activity badge color changes when clicked and resets the number to 0 
           Suggestion: You may want to set a flag when this happens to tick off all checked messages / notifications -->
<span class="activity-dropdown" id="activity">
  <i class="fa fa-user"></i>
  <b class="badge bg-color-red bounceIn animated">
    21
  </b>
</span>

 <!-- AJAX-DROPDOWN : control this dropdown height, look and feel from the LESS variable file -->
<div class="ajax-dropdown">
  
  <!-- the ID links are fetched via AJAX to the ajax container "ajax-notifications" -->
  <div data-toggle="buttons" class="btn-group btn-group-justified">
        <label class="btn btn-default">
          <input type="radio" id="ajax/notify/mail.html" name="activity"> Msgs (14)
        </label>
        <label class="btn btn-default">
          <input type="radio" id="ajax/notify/notifications.html" name="activity"> notify (3)
        </label>
        <label class="btn btn-default">
          <input type="radio" id="ajax/notify/tasks.html" name="activity"> Tasks (4)
        </label>
    </div>
  
  <!-- notification content -->
  <div class="ajax-notifications custom-scroll">
    
    <div class="alert alert-transparent">
      <h4>Click a button to show messages here</h4>
      This blank page message helps protect your privacy, or you can show the first message here automatically.
    </div>
    
    <i class="fa fa-lock fa-4x fa-border"></i>
    
  </div>
  <!-- end notification content -->
  
  <!-- footer: refresh area -->
  <span>
    Last updated on: 12/12/2013 9:43AM
    <button class="btn btn-xs btn-default pull-right" data-loading-text="&lt;i class='fa fa-refresh fa-spin'&gt;&lt;/i&gt; Loading..." type="button">
      <i class="fa fa-refresh"></i>
    </button>
  </span>
  <!-- end footer -->
  
</div>
<!-- END AJAX-DROPDOWN -->
</div>

app/views/common/admin/_projects.html.erb
<!-- projects dropdown -->
<div id="project-context">
  
  <span class="label">Projects:</span>
  <span data-toggle="dropdown" class="popover-trigger-element dropdown-toggle" id="project-selector">Recent projects <i class="fa fa-angle-down"></i></span>
  
  <!-- Suggestion: populate this list with fetch and push technique -->
  <ul class="dropdown-menu">
    <li>
      <a href="javascript:void(0);">Online e-merchant management system - attaching integration with the iOS</a>
    </li>
    <li>
      <a href="javascript:void(0);">Notes on pipeline upgradee</a>
    </li>
    <li>
      <a href="javascript:void(0);">Assesment Report for merchant account</a>
    </li>
    <li class="divider"></li>
    <li>
      <a href="javascript:void(0);"><i class="fa fa-power-off"></i> Clear</a>
    </li>
  </ul>
</div>
  <!-- end dropdown-menu-->

app/views/common/admin/_shortcut_nav.html.erb
<div id="shortcut">
      <ul>
        <li>
          <a class="jarvismetro-tile big-cubes bg-color-blue" href="#ajax/inbox.html">
            <span class="iconbox">
              <i class="fa fa-envelope fa-4x"></i>
              <span>Mail <span class="label pull-right bg-color-darken">14</span></span>
            </span>
          </a>
        </li>
        <li>
          <a class="jarvismetro-tile big-cubes bg-color-orangeDark" href="#ajax/calendar.html">
            <span class="iconbox">
              <i class="fa fa-calendar fa-4x"></i>
              <span>Calendar</span>
            </span>
          </a>
        </li>
        <li>
          <a class="jarvismetro-tile big-cubes bg-color-purple" href="#ajax/gmap-xml.html">
            <span class="iconbox">
              <i class="fa fa-map-marker fa-4x"></i>
              <span>Maps</span>
            </span>
          </a>
        </li>
        <li>
          <a class="jarvismetro-tile big-cubes bg-color-blueDark" href="#ajax/invoice.html">
            <span class="iconbox">
              <i class="fa fa-book fa-4x"></i>
              <span>Invoice <span class="label pull-right bg-color-darken">99</span></span>
            </span>
          </a>
        </li>
        <li>
          <a class="jarvismetro-tile big-cubes bg-color-greenLight" href="#ajax/gallery.html">
            <span class="iconbox">
              <i class="fa fa-picture-o fa-4x"></i>
              <span>Gallery </span>
            </span>
          </a>
        </li>
        <li>
          <a class="jarvismetro-tile big-cubes selected bg-color-pinkDark" href="javascript:void(0);">
            <span class="iconbox">
              <i class="fa fa-user fa-4x"></i>
              <span>My Profile </span>
            </span>
          </a>
        </li>
      </ul>
    </div>

app/views/common/admin/_widget_title.html.erb
<div class="jarviswidget-ctrls" role="menu">  
         <a data-placement="bottom" title="" rel="tooltip" class="button-icon jarviswidget-toggle-btn" href="#" data-original-title="Collapse"><i class="fa fa-minus "></i></a> 
         <a data-placement="bottom" title="" rel="tooltip" class="button-icon jarviswidget-fullscreen-btn" href="javascript:void(0);" data-original-title="Fullscreen"><i class="fa fa-resize-full "></i></a> 
         <a data-placement="bottom" title="" rel="tooltip" class="button-icon jarviswidget-delete-btn" href="javascript:void(0);" data-original-title="Delete"><i class="fa fa-times"></i></a>
        </div>

        <span class="widget-icon"> <i class="fa fa-table"></i> </span>
        <h2><%= title %></h2>

        <span class="jarviswidget-loader"><i class="fa fa-refresh fa-spin"></i></span>