config/routes.rb
  EnterpriseCollab::Application.routes.draw do
  
  devise_for :users, :controllers => {:registrations => "users/registrations"}
  authenticated :user do
    resources :users
    post "users/new_user_create" => "users#new_user_create"
  end

  get "accounts/cron_tasks" => "accounts#cron_tasks"
  resources :accounts

  resources :dashboard

  resources :spaces
  get "spaces/milestones/:id/:filter" => "spaces#milestones"
  get "spaces/team/:id" => "spaces#team"

  resources :groups

  get "standup_reports/daily_email" => "standup_reports#daily_email"
  resources :standup_reports

  root 'home#index'
  

end

app/views/common/_flash_messages.html.erb
<% flash.each do |key, value| %>
  <% flash_class = (key == :alert) ? "danger" : "success"  %>
<div id="flash-message" class="alert alert-<%= flash_class %> fade in col-sm-9">
  <button data-dismiss="alert" class="close">×</button>
   <% icon = "fa-thumbs-o-down" %>
  <i class="fa-fw fa fa-exclamation-triangle"></i>
  <strong><%= key.capitalize %>!</strong> <%= value.html_safe %>
</div>
<% end %>

app/views/common/_header.html.erb
<div id="logo-group">
  <span id="logo"><%= link_to image_tag("smartadmin/logo.png"), root_path %></span>
</div>

<div id="flash-messages">
  <%= render "common/flash_messages", :locals => {flash => flash } %>
</div>
<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
<span id="login-header-space"> 
  <h4 class="hidden-mobile">Need an account?</h4> 
  <%= link_to "Create account", new_registration_path(resource_name), :class=>"btn btn-danger" %>
</span>
<% end -%>

app/views/common/_login.html.erb
<div class="col-xs-12 col-sm-12 col-md-5 col-lg-4">
            <div class="well no-padding">
               <form accept-charset="UTF-8' action="/home/loginattempt" method="post" class="smart-form client-form" id="login-form"  >
                 <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>"/>
                <header>
                  Sign In
                </header>

                <fieldset>
                  
                  <section>
                    <label class="label">E-mail</label>
                    <label class="input"> 
                      <i class="icon-append fa fa-user"></i>
                    <input type="email" name="email">
                      <b class="tooltip tooltip-top-right"><i class="fa fa-user txt-color-teal"></i> Please enter email address/username</b></label>
                  </section>

                  <section>
                    <label class="label">Password</label>
                    <label class="input"> <i class="icon-append fa fa-lock"></i>
                      <input type="password" name="loginpassword">
                      <b class="tooltip tooltip-top-right"><i class="fa fa-lock txt-color-teal"></i> Enter your password</b> </label>
                    <div class="note">
                      <a href="javascript:void(0)">Forgot password?</a>
                    </div>
                  </section>

                  <section>
                    <label class="checkbox">
                      <input type="checkbox" checked="" name="remember">
                      <i></i>Stay signed in</label>
                  </section>
                </fieldset>
                <footer>
                  <button class="btn btn-primary" type="submit">
                    Sign in
                  </button>
                </footer>
              </form>

            </div>
            
            <h5 class="text-center"> - Or sign in using -</h5>
                              
                    <ul class="list-inline text-center">
                      <li>
                        <a class="btn btn-primary btn-circle" href="javascript:void(0);"><i class="fa fa-facebook"></i></a>
                      </li>
                      <li>
                        <a class="btn btn-info btn-circle" href="javascript:void(0);"><i class="fa fa-twitter"></i></a>
                      </li>
                      <li>
                        <a class="btn btn-warning btn-circle" href="javascript:void(0);"><i class="fa fa-linkedin"></i></a>
                      </li>
                    </ul>
            
          </div>  

app/views/common/_login_form.html.erb
<div class="col-xs-12 col-sm-12 col-md-5 col-lg-4">
  <div class="well no-padding">

    <%= form_for(resource, :as => resource_name, :html => {:class => "smart-form client-form", :novalidate=>"novalidate"}, :url => session_path(resource_name)) do |f| %>
      <header>Sign In</header>
     <fieldset>
       <section>
       <%= f.label :email, :class => "label" %>
        <label class="input"><i class="icon-append fa fa-user"></i>
          <%= f.email_field :email, :autofocus => true %>
        <b class="tooltip tooltip-top-right"><i class="fa fa-user txt-color-teal"></i> Please enter email address</b></label>
      </section>

      <section>
        <%= f.label :password, :class => "label" %>
        <label class="input"> <i class="icon-append fa fa-lock"></i>
          <%= f.password_field :password %>
          <b class="tooltip tooltip-top-right"><i class="fa fa-lock txt-color-teal"></i> Enter your password</b> </label>
        <div class="note">
          <%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
            <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
          <% end -%>
        </div>
      </section>

      <% if devise_mapping.rememberable? -%>
        <section>
          <label class="checkbox">
            <%= f.check_box :remember_me %> <%= f.label :remember_me %>
            <i></i>Stay signed in</label>
        </section>
      
      </fieldset>
      <% end -%>

      <footer>
        <%= f.submit "Sign in", :class => "btn btn-primary" %>
      </footer>

    <% end %>
  </div>
</div>

<script type="text/javascript">
      runAllForms();

      $(function() {
        // Validation
        $("#login-form").validate({
          // Rules for form validation
          rules : {
            email : {
              required : true,
              email : true
            },
            password : {
              required : true,
              minlength : 3,
              maxlength : 20
            }
          },

          // Messages for form validation
          messages : {
            email : {
              required : 'Please enter your email address',
              email : 'Please enter a VALID email address'
            },
            password : {
              required : 'Please enter your password'
            }
          },

          // Do not change code below
          errorPlacement : function(error, element) {
            error.insertAfter(element.parent());
          }
        });
      });
    </script>



<% if false %>
<div class="col-xs-12 col-sm-12 col-md-5 col-lg-4">
            <div class="well no-padding">
              <form class="smart-form client-form" id="login-form" action="index.html" novalidate="novalidate">
                <header>
                  Sign In
                </header>

                <fieldset>
                  
                  <section>
                    <label class="label">E-mail</label>
                    <label class="input"> 
                      <i class="icon-append fa fa-user"></i>
                    <input type="email" name="email">
                      <b class="tooltip tooltip-top-right"><i class="fa fa-user txt-color-teal"></i> Please enter email address/username</b></label>
                  </section>

                  <section>
                    <label class="label">Password</label>
                    <label class="input"> <i class="icon-append fa fa-lock"></i>
                      <input type="password" name="password">
                      <b class="tooltip tooltip-top-right"><i class="fa fa-lock txt-color-teal"></i> Enter your password</b> </label>
                    <div class="note">
                      <a href="javascript:void(0)">Forgot password?</a>
                    </div>
                  </section>

                  <section>
                    <label class="checkbox">
                      <input type="checkbox" checked="" name="remember">
                      <i></i>Stay signed in</label>
                  </section>
                </fieldset>
                <footer>
                  <button class="btn btn-primary" type="submit">
                    Sign in
                  </button>
                </footer>
              </form>

            </div>
            
            <h5 class="text-center"> - Or sign in using -</h5>
                              
                    <ul class="list-inline text-center">
                      <li>
                        <a class="btn btn-primary btn-circle" href="javascript:void(0);"><i class="fa fa-facebook"></i></a>
                      </li>
                      <li>
                        <a class="btn btn-info btn-circle" href="javascript:void(0);"><i class="fa fa-twitter"></i></a>
                      </li>
                      <li>
                        <a class="btn btn-warning btn-circle" href="javascript:void(0);"><i class="fa fa-linkedin"></i></a>
                      </li>
                    </ul>
            
          </div>  

<% end %>

app/views/common/_reg_header.html.erb
 <div id="logo-group">
      <span id="logo"> <%= image_tag("smartadmin/logo.png")%></span>

      <!-- END AJAX-DROPDOWN -->
    </div>