config/routes.rb
  EnterpriseCollab::Application.routes.draw do
  
  devise_for :users, :controllers => {:registrations => "users/registrations"}
  authenticated :user do
    resources :users
    post "users/new_user_create" => "users#new_user_create"
  end

  get "accounts/cron_tasks" => "accounts#cron_tasks"
  resources :accounts

  resources :dashboard

  resources :spaces
  get "spaces/milestones/:id/:filter" => "spaces#milestones"
  get "spaces/team/:id" => "spaces#team"

  resources :groups

  get "standup_reports/daily_email" => "standup_reports#daily_email"
  resources :standup_reports

  root 'home#index'
  

end

app/models/account.rb
class Account < ActiveRecord::Base
  has_many :users, :dependent => :destroy
  has_many :groups, :dependent => :destroy
  has_many :standup_reports, :dependent => :destroy

  validates :company_name, :presence => true
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_filter :authenticate_user!

 
  # # Add a user by Admin
  # def new_user
  #   @users = User.all
  #   # render :text => "Add User", :layout => "application"
  # end  

  def edit
    
  end

end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<div class="col-xs-12 col-sm-12 col-md-7 col-lg-7 hidden-xs hidden-sm"> 
    <h1 class="txt-color-red login-header-big">New Account</h1> 
      <div class="hero"> 
 
      <div class="pull-left login-desc-box-l"> 
            <h4 class="paragraph-header">It's Okay to be Smart. Experience the simplicity of SmartAdmin, everywhere you go!</h4> 
        <div class="login-app-icons"> 
          <a class="btn btn-danger btn-sm" href="javascript:void(0);">Frontend Template</a> 
          <a class="btn btn-danger btn-sm" href="javascript:void(0);">Find out more</a> 
        </div> 
      </div> 
      <div class="pull-right display-image"> 
     <%= image_tag('smartadmin/iphoneview.png', :width =>'210' ) %> 
      </div> 
 
      </div> 

      <div class="row"> 
      <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6"> 
          <h5 class="about-heading">About SmartAdmin - Are you up to date?</h5> 
          <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa. </p> 
      </div> 
      <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6"> 
        <h5 class="about-heading">Not just your average template!</h5> 
          <p> Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi voluptatem accusantium! </p> 
      </div> 
    </div> 
</div> 
 
<%= form_for(@account) do |f| %> 
  <% if @account.errors.any? %> 
    <div id="error_explanation"> 
    <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2> 
       <ul> 
        <% @account.errors.full_messages.each do |msg| %> 
           <li><%= msg %></li> 
         <% end %> 
      </ul> 
    </div> 
  <% end %> 
 
    <div class="col-xs-12 col-sm-12 col-md-5 col-lg-5"> 
      <div class="well no-padding"> 
 
    <h3> User Information<br> </h3> 
  
  <p> 
    <label for="company">Company</label><br/> 
    <%= f.text_field :company %> 
  </p> 

  <p> 
    <label for="subdomain">Sub-Domain</label><br/> 
    <%= f.text_field :subdomain %> 
  </p> 

  <p> 
    <label for="address">Address</label><br/> 
    <%= f.text_field :address %> 
  </p> 

  <p> 
    <label for="city">City</label><br/> 
    <%= f.text_field :city %> 
  </p> 
  
  <p> 
    <label for="state">State</label><br/> 
    <%= f.text_field :state %> 
  </p> 

  <p> 
    <label for="zipcode">ZipCode</label><br/> 
    <%= f.text_field :zipcode %> 
  </p> 

  <p> 
    <label for="country">Country</label><br/> 
    <%= f.text_field :country %> 
  </p> 
  
  <p> 
    <label for="office">Office Number</label><br/> 
    <%= f.telephone_field :office %> 
  </p> 
  
  <p> 
    <label for="mobile">Mobile Number</label><br/> 
    <%= f.telephone_field :mobile %> 
  </p> 

  <section> 
  <label class="select"> 
    <select name="status"> 
    <option disabled="" selected="" value="0">Status</option> 
    <option value="1">Single</option> 
    <option value="2">Married</option> 
    </select> <i></i> 
  </label> 
  </section> 

  <footer> 
    <button class="btn btn-primary" type="submit">Save Application</button> 
  </footer> 
<% end %> 

app/views/accounts/activate.html.erb
<%= form_for(@account) do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 
<div class="col-xs-12 col-sm-12 col-md-5 col-lg-5">
            <div class="well no-padding">

                <header>
                  Activate  your Account
              <br>
                </header>
<div class="field">
    <%= f.label :Userid %><br>
    <%= f.text_field :userid %>
  </div>

 <span id="login-header-space">  <a class="btn btn-danger" href="s/new"> Activate</a> </span>
  
  <% end %>

app/views/accounts/cron_tasks.html.erb
<div class="row">
  <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12 sortable-grid ui-sortable">
    <div id="wid-id-0" class="jarviswidget jarviswidget-color-darken jarviswidget-sortable">
      <header role="heading">
        <%= render :partial => "common/admin/widget_title", :locals => {:title => "Cron Tasks"} %>
      </header>
      <div role="content">

          <!-- widget edit box -->
          <div class="jarviswidget-editbox">
            <!-- This area used as dropdown edit box -->

          </div>
          <!-- end widget edit box -->

          <!-- widget content -->
          <div id="widget-content" class="widget-body">
            <div>If Cron is not running run these tasks manually based on their frequency.</div>
            <ul class="list-group">
              <li class="list-group-item"><%= link_to '<i class="fa fa-lg fa-fw fa-cog"></i>  <span class="menu-item-parent">Send-out StandUp Reports</span>'.html_safe, {controller: "standup_reports", action: "daily_email"}, "data-remote" => true  %><span id="daily_email"></span></li>
            </ul>

          </div> <!-- ENDs widget-content -->

        </div>

    </div>
  </article>

</div>

app/views/accounts/edit.html.erb
<div class="row">
  <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12 sortable-grid ui-sortable">
    <div id="wid-id-0" class="jarviswidget jarviswidget-color-darken jarviswidget-sortable">
      <header role="heading">
        <%= render :partial => "common/admin/widget_title", :locals => {:title => "Organization Account"} %>
      </header>
      <div role="content">

          <!-- widget edit box -->
          <div class="jarviswidget-editbox">
            <!-- This area used as dropdown edit box -->

          </div>
          <!-- end widget edit box -->

          <!-- widget content -->
          <div id="widget-content" class="widget-body">
            <div>Update your organization account details.</div>
            <h2>TODO - Account Update form</h2>

          </div> <!-- ENDs widget-content -->

        </div>

    </div>
  </article>

</div>

app/views/accounts/index.html.erb
<h1>Accounts#index</h1>
<p>Find me in app/views/accounts/index.html.erb</p>

app/views/accounts/new.html.erb
<%= render 'form' %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Company:</strong>
  <%= @account.company %>
</p>

<p>
  <strong>Subdomain:</strong>
  <%= @account.subdomain %>
</p>

<p>
  <strong>Address:</strong>
  <%= @account.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @account.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @account.state %>
</p>

<p>
  <strong>Zipcode:</strong>
  <%= @account.zipcode %>
</p>

<p>
  <strong>Country:</strong>
  <%= @account.country %>
</p>

<p>
  <strong>Office:</strong>
  <%= @account.office %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @account.mobile %>
</p>

<p>
  <strong>Status:</strong>
  <%= @account.status %>
  
<br/>
<p> <%= link_to 'Update Account', edit_account_path(@account) %> </p>
        
<br/>
    <p><%= link_to 'Create New Account', new_account_path %></p>

<br/>
  <p><%= link_to 'Display Dashboard', dashboard_path %> </p>
   